name: Build
on: push
jobs:
    build:
        strategy:
            matrix:
                include:
                    - os: windows-latest
                      command: package-windows-x64
                    - os: ubuntu-latest
                      command: package-linux-x64
                    - os: macos-latest
                      command: package-macos-x64
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: 'true'
            - name: Install Node.js
              uses: actions/setup-node@v4
            - name: Install dependencies for the client
              run: npm ci
            - name: Install dependencies for the language server
              run: npm ci
              working-directory: ./GLSL-Language-Server
            - name: Build in production mode
              run: npm run build-production
            - name: ESLint
              run: npm run eslint
            - name: Prettier lint
              run: npm run prettier-lint
            - name: Build the tests
              run: npm run build-tests
            - name: Run tests
              run: xvfb-run -a npm test
              if: runner.os == 'Linux'
            # FIXME: Tests don't seem to work on Mac OS
            - name: Run tests
              run: npm test
              if: runner.os == 'Windows'
            - name: Create platform-specific package
              run: npm run ${{ matrix.command }}
            - name: Create Universal package
              run: npm run package-universal
